# Generated by Django 6.0 on 2026-03-23 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('extension', models.CharField(max_length=20)),
                ('icon', models.FileField(blank=True, null=True, upload_to='language_icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignments.language'),
        ),
    ]
