# Generated by Django 6.0 on 2026-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingsession',
            name='burst_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typingsession',
            name='requires_human_review',
            field=models.BooleanField(default=False),
        ),
    ]
