# Generated by Django 6.0 on 2026-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_tracker', '0002_typingsession_burst_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingsession',
            name='has_started_typing',
            field=models.BooleanField(default=False),
        ),
    ]
